# Generated by Django 4.2.9 on 2024-01-14 01:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadednotes',
            name='content',
            field=models.FileField(default=core.models.default_file, upload_to='store/pdfs/'),
        ),
    ]
